### ISSUE TITLE
Ability to define topology diagram from gns3fy

### ISSUE THREAD

**Issue by davidban77** [davidban77/gns3fy#57]
I am thinking of being able of defining topologies diagrams with the help of the `Drawing` endpoint added. In general terms, something like:

- Specify a *topology diagram*, which can be something like access-distribution-code, spine-leaf, or maybe general sections (like section A and section B denoted as a rectangle or circle)
- Make the node re-arrenage themselves depending on the *section* they are in, I think this will involve some good math :)

**Comment by Krlosromero** [comment]
some progress on create & delete drawing methods, but there seems to be a bug on GNS3 Api

**Comment by davidban77** [comment]
Can you try to change the height/width attributes of a drawing to see if that is reflected instead?

**Comment by davidban77** [comment]
I think this will be out of scope for the main package. Beside the method created to arrange the devices in a circular fashion, other methods should be external to the library.

I created a [blog post](https://davidban77.hashnode.dev/making-your-network-topology-come-to-virtual-life-with-drawthenet-and-gns3fy-ck9kjsujb004jzss19c5stx6t) that uses drawthe.net YAML files to recreate GNS3 topologies.
